### ISSUE TITLE
Missing default top N indices when there are no GT boxes

### ISSUE THREAD

**Issue by bencwallace** [henrylee2570/NoisyAnchor#1]
Hi there. Thanks for very much for making your code public!

I've been experimenting with this repository and have encountered an error during training on a custom dataset. Namely, after a few hundred iterations, I got the following error:

```
ERROR [04/12 14:58:31 d2.engine.train_loop]: Exception during training:                                                                                                                                             
Traceback (most recent call last):                                                                                                                                                                                  
  File "/home/root/NoisyAnchor/detectron2/engine/train_loop.py", line 132, in train                                                                                                                                 
    self.run_step()                                                                                                                                                                                                 
  File "/home/root/NoisyAnchor/detectron2/engine/train_loop.py", line 215, in run_step                                                                                                                              
    loss_dict = self.model(data)                                                                                                                                                                                    
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl                                                                                                                 
    result = self.forward(*input, **kwargs)                                                                                                                                                                         
  File "/home/root/NoisyAnchor/detectron2/modeling/meta_arch/retinanet_noisy.py", line 220, in forward                                                                                                              
    gt_classes, gt_anchors_reg_deltas, soft_labels, reweight_coeffs = self.get_ground_truth(anchors, gt_instances, box_cls, box_delta)                                                                              
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context                                                                                                           
    return func(*args, **kwargs)                                                                                                                                                                                    
  File "/home/root/NoisyAnchor/detectron2/modeling/meta_arch/retinanet_noisy.py", line 364, in get_ground_truth                                                           
    gt_matched_idxs, anchor_labels, topN_inds = self.matcher(match_quality_matrix)                                                                                                                                  
ValueError: not enough values to unpack (expected 3, got 2)                                                     
```

Digging a bit deeper, I noticed that when there are no ground truth boxes in an example, only two objects are returned when calling `MatcherTopN` (see [here](https://github.com/henrylee2570/NoisyAnchor/blob/80c7c250027ddc6616b98b44f488c9088faccfe7/detectron2/modeling/matcher.py#L180)). However, three objects are expected in the training loop (see [here](https://github.com/henrylee2570/NoisyAnchor/blob/80c7c250027ddc6616b98b44f488c9088faccfe7/detectron2/modeling/meta_arch/retinanet_noisy.py#L364)).

I'm guessing some kind of `default_topN_indices` needs to be returned, though I'm not sure what would be most appropriate.

Thanks!

**Comment by henrylee2570** [comment]
Thanks for the interest in our work! 

Yes you are right, this issue wasn't noticed before as `DATALOADER.FILTER_EMPTY_ANNOTATIONS` is set to be True by default to filter out images with no annotations. I've pushed a commit to fix it, could you pull and check if it works on your side?

**Comment by bencwallace** [comment]
Thanks for the quick response.

> `DATALOADER.FILTER_EMPTY_ANNOTATIONS` is set to be True by default to filter out images with no annotations

This is true, but it seems that the [mapper](https://github.com/henrylee2570/NoisyAnchor/blob/master/detectron2/data/dataset_mapper.py) was re-introducing such instances (I didn't isolate exactly how).

> I've pushed a commit to fix it, could you pull and check if it works on your side?

I've tested the updated version and there seem to be no problems. Thanks very much!

**Comment by henrylee2570** [comment]
> This is true, but it seems that the mapper was re-introducing such instances (I didn't isolate exactly how). I've tested the updated version and there seem to be no problems. Thanks very much!

I see, thanks for the catch! In this case I'll close it for now, feel free to open if any issue arises.
